/**
 * generated by Xtext
 */
package org.example.domainmodel.validation;

import org.example.domainmodel.validation.AbstractDomainmodelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DomainmodelValidator extends AbstractDomainmodelValidator {
}
