/*
 * generated by Xtext
 */
package com.nagarro.ui.contentassist

import com.nagarro.ui.contentassist.AbstractAppBuilderDSLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AppBuilderDSLProposalProvider extends AbstractAppBuilderDSLProposalProvider {
}
