/*
 * generated by Xtext
 */
package org.example.domainmodel.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.example.domainmodel.services.DomainmodelGrammarAccess;

public class DomainmodelParser extends AbstractContentAssistParser {
	
	@Inject
	private DomainmodelGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.example.domainmodel.ui.contentassist.antlr.internal.InternalDomainmodelParser createParser() {
		org.example.domainmodel.ui.contentassist.antlr.internal.InternalDomainmodelParser result = new org.example.domainmodel.ui.contentassist.antlr.internal.InternalDomainmodelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getAbstractNamespaceElementAccess().getAlternatives(), "rule__AbstractNamespaceElement__Alternatives");
					put(grammarAccess.getFeatureMappingOptionsAccess().getAlternatives(), "rule__FeatureMappingOptions__Alternatives");
					put(grammarAccess.getRestMethodCallAccess().getAlternatives(), "rule__RestMethodCall__Alternatives");
					put(grammarAccess.getInterfaceOperationUsageRuleAccess().getAlternatives_0(), "rule__InterfaceOperationUsageRule__Alternatives_0");
					put(grammarAccess.getViewElementAccess().getAlternatives(), "rule__ViewElement__Alternatives");
					put(grammarAccess.getBindSourceAccess().getAlternatives(), "rule__BindSource__Alternatives");
					put(grammarAccess.getInitActionFeatureAccess().getAlternatives(), "rule__InitActionFeature__Alternatives");
					put(grammarAccess.getValidatorRuleAccess().getAlternatives(), "rule__ValidatorRule__Alternatives");
					put(grammarAccess.getSetRestCallReceiverIDParameterAccess().getAlternatives_0(), "rule__SetRestCallReceiverIDParameter__Alternatives_0");
					put(grammarAccess.getSetRestCallReceiverParameterAccess().getAlternatives(), "rule__SetRestCallReceiverParameter__Alternatives");
					put(grammarAccess.getSetActionReceiverAccess().getAlternatives(), "rule__SetActionReceiver__Alternatives");
					put(grammarAccess.getInterfaceMethodCallParameterAccess().getParameterTypeAlternatives_2_0(), "rule__InterfaceMethodCallParameter__ParameterTypeAlternatives_2_0");
					put(grammarAccess.getUIActionFeatureAccess().getAlternatives(), "rule__UIActionFeature__Alternatives");
					put(grammarAccess.getControllerElementAccess().getAlternatives(), "rule__ControllerElement__Alternatives");
					put(grammarAccess.getScreenModuleAccess().getAlternatives(), "rule__ScreenModule__Alternatives");
					put(grammarAccess.getMainFeatureOptionAccess().getAlternatives_0(), "rule__MainFeatureOption__Alternatives_0");
					put(grammarAccess.getUIFeatureAccess().getAlternatives(), "rule__UIFeature__Alternatives");
					put(grammarAccess.getBusinessFeatureTypeAccess().getAlternatives(), "rule__BusinessFeatureType__Alternatives");
					put(grammarAccess.getSystemModuleAccess().getAlternatives(), "rule__SystemModule__Alternatives");
					put(grammarAccess.getContentElementLiteralAccess().getAlternatives(), "rule__ContentElementLiteral__Alternatives");
					put(grammarAccess.getPropertyNameLiteralAccess().getAlternatives(), "rule__PropertyNameLiteral__Alternatives");
					put(grammarAccess.getContainerElementLiteralAccess().getAlternatives(), "rule__ContainerElementLiteral__Alternatives");
					put(grammarAccess.getUIElementReceiverKeyAccess().getAlternatives(), "rule__UIElementReceiverKey__Alternatives");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
					put(grammarAccess.getDataTypeAccess().getGroup_5(), "rule__DataType__Group_5__0");
					put(grammarAccess.getNamespaceDeclarationAccess().getGroup(), "rule__NamespaceDeclaration__Group__0");
					put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
					put(grammarAccess.getFeatureAccess().getGroup_2(), "rule__Feature__Group_2__0");
					put(grammarAccess.getDomainEntityAccess().getGroup(), "rule__DomainEntity__Group__0");
					put(grammarAccess.getRestOperationAccess().getGroup(), "rule__RestOperation__Group__0");
					put(grammarAccess.getMethodParameterAccess().getGroup(), "rule__MethodParameter__Group__0");
					put(grammarAccess.getMethodParametersAccess().getGroup(), "rule__MethodParameters__Group__0");
					put(grammarAccess.getMethodParametersAccess().getGroup_1(), "rule__MethodParameters__Group_1__0");
					put(grammarAccess.getMethodCallAccess().getGroup(), "rule__MethodCall__Group__0");
					put(grammarAccess.getInterfaceOperationAccess().getGroup(), "rule__InterfaceOperation__Group__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup(), "rule__InterfaceDeclaration__Group__0");
					put(grammarAccess.getInterfaceOperationUsageRuleAccess().getGroup(), "rule__InterfaceOperationUsageRule__Group__0");
					put(grammarAccess.getInterfaceOperationsUsageRuleAccess().getGroup(), "rule__InterfaceOperationsUsageRule__Group__0");
					put(grammarAccess.getStatelessComponentAccess().getGroup(), "rule__StatelessComponent__Group__0");
					put(grammarAccess.getDomainRepositoryAccess().getGroup(), "rule__DomainRepository__Group__0");
					put(grammarAccess.getEntryParametersModuleAccess().getGroup(), "rule__EntryParametersModule__Group__0");
					put(grammarAccess.getModelFeatureAccess().getGroup(), "rule__ModelFeature__Group__0");
					put(grammarAccess.getModelFeatureAccess().getGroup_3(), "rule__ModelFeature__Group_3__0");
					put(grammarAccess.getModelModuleAccess().getGroup(), "rule__ModelModule__Group__0");
					put(grammarAccess.getElementFeatureAccess().getGroup(), "rule__ElementFeature__Group__0");
					put(grammarAccess.getContentElementAccess().getGroup(), "rule__ContentElement__Group__0");
					put(grammarAccess.getContentElementAccess().getGroup_3(), "rule__ContentElement__Group_3__0");
					put(grammarAccess.getContentElementAccess().getGroup_3_1(), "rule__ContentElement__Group_3_1__0");
					put(grammarAccess.getContainerElementAccess().getGroup(), "rule__ContainerElement__Group__0");
					put(grammarAccess.getContainerElementAccess().getGroup_2(), "rule__ContainerElement__Group_2__0");
					put(grammarAccess.getContainerElementAccess().getGroup_2_2(), "rule__ContainerElement__Group_2_2__0");
					put(grammarAccess.getContainerElementAccess().getGroup_3(), "rule__ContainerElement__Group_3__0");
					put(grammarAccess.getViewModuleAccess().getGroup(), "rule__ViewModule__Group__0");
					put(grammarAccess.getValidateActionAccess().getGroup(), "rule__ValidateAction__Group__0");
					put(grammarAccess.getAttachActionAccess().getGroup(), "rule__AttachAction__Group__0");
					put(grammarAccess.getBindEnumSourceAccess().getGroup(), "rule__BindEnumSource__Group__0");
					put(grammarAccess.getBindActionAccess().getGroup(), "rule__BindAction__Group__0");
					put(grammarAccess.getBindActionAccess().getGroup_2(), "rule__BindAction__Group_2__0");
					put(grammarAccess.getInitActionModuleAccess().getGroup(), "rule__InitActionModule__Group__0");
					put(grammarAccess.getValidatorRulesAccess().getGroup(), "rule__ValidatorRules__Group__0");
					put(grammarAccess.getValidatorRulesAccess().getGroup_1(), "rule__ValidatorRules__Group_1__0");
					put(grammarAccess.getValidatorFeatureAccess().getGroup(), "rule__ValidatorFeature__Group__0");
					put(grammarAccess.getValidatorModuleAccess().getGroup(), "rule__ValidatorModule__Group__0");
					put(grammarAccess.getScreenModelParameterAccess().getGroup(), "rule__ScreenModelParameter__Group__0");
					put(grammarAccess.getScreenModelParametersAccess().getGroup(), "rule__ScreenModelParameters__Group__0");
					put(grammarAccess.getScreenModelParametersAccess().getGroup_1(), "rule__ScreenModelParameters__Group_1__0");
					put(grammarAccess.getNavigateToActionAccess().getGroup(), "rule__NavigateToAction__Group__0");
					put(grammarAccess.getNavigateToActionAccess().getGroup_2(), "rule__NavigateToAction__Group_2__0");
					put(grammarAccess.getExecuteActionAccess().getGroup(), "rule__ExecuteAction__Group__0");
					put(grammarAccess.getSetRestCallReceiverURLParameterAccess().getGroup(), "rule__SetRestCallReceiverURLParameter__Group__0");
					put(grammarAccess.getSetRestCallReceiverReturnTypeParameterAccess().getGroup(), "rule__SetRestCallReceiverReturnTypeParameter__Group__0");
					put(grammarAccess.getSetRestCallReceiverIDParameterAccess().getGroup(), "rule__SetRestCallReceiverIDParameter__Group__0");
					put(grammarAccess.getSetRestCallReceiverParametersAccess().getGroup(), "rule__SetRestCallReceiverParameters__Group__0");
					put(grammarAccess.getSetRestCallReceiverParametersAccess().getGroup_1(), "rule__SetRestCallReceiverParameters__Group_1__0");
					put(grammarAccess.getSetRestCallReceiverAccess().getGroup(), "rule__SetRestCallReceiver__Group__0");
					put(grammarAccess.getSetUIElementReceiverAccess().getGroup(), "rule__SetUIElementReceiver__Group__0");
					put(grammarAccess.getSetActionAccess().getGroup(), "rule__SetAction__Group__0");
					put(grammarAccess.getInterfaceMethodCallParameterAccess().getGroup(), "rule__InterfaceMethodCallParameter__Group__0");
					put(grammarAccess.getInterfaceMethodCallParametersAccess().getGroup(), "rule__InterfaceMethodCallParameters__Group__0");
					put(grammarAccess.getInterfaceMethodCallParametersAccess().getGroup_1(), "rule__InterfaceMethodCallParameters__Group_1__0");
					put(grammarAccess.getInterfaceMethodCallAccess().getGroup(), "rule__InterfaceMethodCall__Group__0");
					put(grammarAccess.getUIActionModuleAccess().getGroup(), "rule__UIActionModule__Group__0");
					put(grammarAccess.getControllerModuleAccess().getGroup(), "rule__ControllerModule__Group__0");
					put(grammarAccess.getScreenFeatureAccess().getGroup(), "rule__ScreenFeature__Group__0");
					put(grammarAccess.getMainFeatureOptionAccess().getGroup(), "rule__MainFeatureOption__Group__0");
					put(grammarAccess.getMainFeatureAccess().getGroup(), "rule__MainFeature__Group__0");
					put(grammarAccess.getMainFeatureAccess().getGroup_3(), "rule__MainFeature__Group_3__0");
					put(grammarAccess.getUIModuleAccess().getGroup(), "rule__UIModule__Group__0");
					put(grammarAccess.getBusinessFeatureAccess().getGroup(), "rule__BusinessFeature__Group__0");
					put(grammarAccess.getBusinessFeatureAccess().getGroup_4(), "rule__BusinessFeature__Group_4__0");
					put(grammarAccess.getBusinessFeaturesAccess().getGroup(), "rule__BusinessFeatures__Group__0");
					put(grammarAccess.getBusinessModuleAccess().getGroup(), "rule__BusinessModule__Group__0");
					put(grammarAccess.getSystemDefinitionAccess().getGroup(), "rule__SystemDefinition__Group__0");
					put(grammarAccess.getDomainmodelAccess().getElementsAssignment(), "rule__Domainmodel__ElementsAssignment");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getDataTypeAccess().getNameAssignment_1(), "rule__DataType__NameAssignment_1");
					put(grammarAccess.getDataTypeAccess().getMappedTypeAssignment_3(), "rule__DataType__MappedTypeAssignment_3");
					put(grammarAccess.getDataTypeAccess().getInitValueAssignment_5_1(), "rule__DataType__InitValueAssignment_5_1");
					put(grammarAccess.getNamespaceDeclarationAccess().getNameAssignment_1(), "rule__NamespaceDeclaration__NameAssignment_1");
					put(grammarAccess.getNamespaceDeclarationAccess().getNamespaceElementsAssignment_3(), "rule__NamespaceDeclaration__NamespaceElementsAssignment_3");
					put(grammarAccess.getFeatureAccess().getNameAssignment_1(), "rule__Feature__NameAssignment_1");
					put(grammarAccess.getFeatureAccess().getMappingOptionAssignment_2_0(), "rule__Feature__MappingOptionAssignment_2_0");
					put(grammarAccess.getFeatureAccess().getMapNameAssignment_2_1(), "rule__Feature__MapNameAssignment_2_1");
					put(grammarAccess.getFeatureAccess().getTypeAssignment_4(), "rule__Feature__TypeAssignment_4");
					put(grammarAccess.getDomainEntityAccess().getNameAssignment_1(), "rule__DomainEntity__NameAssignment_1");
					put(grammarAccess.getDomainEntityAccess().getFeaturesAssignment_3(), "rule__DomainEntity__FeaturesAssignment_3");
					put(grammarAccess.getMethodParameterAccess().getTypeAssignment_0(), "rule__MethodParameter__TypeAssignment_0");
					put(grammarAccess.getMethodParameterAccess().getNameAssignment_1(), "rule__MethodParameter__NameAssignment_1");
					put(grammarAccess.getMethodParametersAccess().getParametersAssignment_0(), "rule__MethodParameters__ParametersAssignment_0");
					put(grammarAccess.getMethodParametersAccess().getParametersAssignment_1_1(), "rule__MethodParameters__ParametersAssignment_1_1");
					put(grammarAccess.getMethodCallAccess().getNameAssignment_0(), "rule__MethodCall__NameAssignment_0");
					put(grammarAccess.getMethodCallAccess().getParametersAssignment_2(), "rule__MethodCall__ParametersAssignment_2");
					put(grammarAccess.getInterfaceOperationAccess().getRestOperationAssignment_1(), "rule__InterfaceOperation__RestOperationAssignment_1");
					put(grammarAccess.getInterfaceOperationAccess().getMethodCallAssignment_2(), "rule__InterfaceOperation__MethodCallAssignment_2");
					put(grammarAccess.getInterfaceOperationAccess().getTypeAssignment_4(), "rule__InterfaceOperation__TypeAssignment_4");
					put(grammarAccess.getInterfaceDeclarationAccess().getNameAssignment_1(), "rule__InterfaceDeclaration__NameAssignment_1");
					put(grammarAccess.getInterfaceDeclarationAccess().getOperationsAssignment_3(), "rule__InterfaceDeclaration__OperationsAssignment_3");
					put(grammarAccess.getInterfaceOperationUsageRuleAccess().getNameAssignment_1(), "rule__InterfaceOperationUsageRule__NameAssignment_1");
					put(grammarAccess.getInterfaceOperationUsageRuleAccess().getInterfaceNameAssignment_3(), "rule__InterfaceOperationUsageRule__InterfaceNameAssignment_3");
					put(grammarAccess.getInterfaceOperationsUsageRuleAccess().getUsageOperationsAssignment_0(), "rule__InterfaceOperationsUsageRule__UsageOperationsAssignment_0");
					put(grammarAccess.getInterfaceOperationsUsageRuleAccess().getUsageOperationsAssignment_1(), "rule__InterfaceOperationsUsageRule__UsageOperationsAssignment_1");
					put(grammarAccess.getStatelessComponentAccess().getNameAssignment_1(), "rule__StatelessComponent__NameAssignment_1");
					put(grammarAccess.getStatelessComponentAccess().getOperationsAssignment_3(), "rule__StatelessComponent__OperationsAssignment_3");
					put(grammarAccess.getDomainRepositoryAccess().getEntityTypeAssignment_2(), "rule__DomainRepository__EntityTypeAssignment_2");
					put(grammarAccess.getDomainRepositoryAccess().getNameAssignment_3(), "rule__DomainRepository__NameAssignment_3");
					put(grammarAccess.getDomainRepositoryAccess().getOperationsAssignment_5(), "rule__DomainRepository__OperationsAssignment_5");
					put(grammarAccess.getEntryParametersModuleAccess().getEntryFeaturesAssignment_2(), "rule__EntryParametersModule__EntryFeaturesAssignment_2");
					put(grammarAccess.getEntryParametersModuleAccess().getEntryFeaturesAssignment_3(), "rule__EntryParametersModule__EntryFeaturesAssignment_3");
					put(grammarAccess.getModelFeatureAccess().getNameAssignment_0(), "rule__ModelFeature__NameAssignment_0");
					put(grammarAccess.getModelFeatureAccess().getTypeAssignment_2(), "rule__ModelFeature__TypeAssignment_2");
					put(grammarAccess.getModelModuleAccess().getModelFeaturesAssignment_2(), "rule__ModelModule__ModelFeaturesAssignment_2");
					put(grammarAccess.getModelModuleAccess().getModelFeaturesAssignment_3(), "rule__ModelModule__ModelFeaturesAssignment_3");
					put(grammarAccess.getElementFeatureAccess().getPropertyNameAssignment_0(), "rule__ElementFeature__PropertyNameAssignment_0");
					put(grammarAccess.getElementFeatureAccess().getPropertyValueAssignment_2(), "rule__ElementFeature__PropertyValueAssignment_2");
					put(grammarAccess.getContentElementAccess().getContentElementAssignment_0(), "rule__ContentElement__ContentElementAssignment_0");
					put(grammarAccess.getContentElementAccess().getNameAssignment_1(), "rule__ContentElement__NameAssignment_1");
					put(grammarAccess.getContentElementAccess().getFeaturesAssignment_3_0(), "rule__ContentElement__FeaturesAssignment_3_0");
					put(grammarAccess.getContentElementAccess().getFeaturesAssignment_3_1_1(), "rule__ContentElement__FeaturesAssignment_3_1_1");
					put(grammarAccess.getContainerElementAccess().getContainerAssignment_0(), "rule__ContainerElement__ContainerAssignment_0");
					put(grammarAccess.getContainerElementAccess().getNameAssignment_1(), "rule__ContainerElement__NameAssignment_1");
					put(grammarAccess.getContainerElementAccess().getFeaturesAssignment_2_1(), "rule__ContainerElement__FeaturesAssignment_2_1");
					put(grammarAccess.getContainerElementAccess().getFeaturesAssignment_2_2_1(), "rule__ContainerElement__FeaturesAssignment_2_2_1");
					put(grammarAccess.getContainerElementAccess().getElementsAssignment_3_1(), "rule__ContainerElement__ElementsAssignment_3_1");
					put(grammarAccess.getContainerElementAccess().getElementsAssignment_3_2(), "rule__ContainerElement__ElementsAssignment_3_2");
					put(grammarAccess.getViewModuleAccess().getElementsAssignment_2(), "rule__ViewModule__ElementsAssignment_2");
					put(grammarAccess.getValidateActionAccess().getConditionAssignment_1(), "rule__ValidateAction__ConditionAssignment_1");
					put(grammarAccess.getValidateActionAccess().getUiReceiverAssignment_3(), "rule__ValidateAction__UiReceiverAssignment_3");
					put(grammarAccess.getAttachActionAccess().getUiActionAssignment_1(), "rule__AttachAction__UiActionAssignment_1");
					put(grammarAccess.getAttachActionAccess().getUiReceiverAssignment_3(), "rule__AttachAction__UiReceiverAssignment_3");
					put(grammarAccess.getBindEnumSourceAccess().getEnumTypeAssignment_4(), "rule__BindEnumSource__EnumTypeAssignment_4");
					put(grammarAccess.getBindSourceAccess().getModelFeatureNameAssignment_0(), "rule__BindSource__ModelFeatureNameAssignment_0");
					put(grammarAccess.getBindActionAccess().getBindSourceAssignment_1(), "rule__BindAction__BindSourceAssignment_1");
					put(grammarAccess.getBindActionAccess().getAttributeAssignment_2_1(), "rule__BindAction__AttributeAssignment_2_1");
					put(grammarAccess.getBindActionAccess().getUiReceiverAssignment_4(), "rule__BindAction__UiReceiverAssignment_4");
					put(grammarAccess.getInitActionModuleAccess().getInitActionFeaturesAssignment_2(), "rule__InitActionModule__InitActionFeaturesAssignment_2");
					put(grammarAccess.getInitActionModuleAccess().getInitActionFeaturesAssignment_3(), "rule__InitActionModule__InitActionFeaturesAssignment_3");
					put(grammarAccess.getValidatorRuleAccess().getStringRuleAssignment_0(), "rule__ValidatorRule__StringRuleAssignment_0");
					put(grammarAccess.getValidatorRuleAccess().getConditionNameAssignment_1(), "rule__ValidatorRule__ConditionNameAssignment_1");
					put(grammarAccess.getValidatorRulesAccess().getValidatorRulesAssignment_0(), "rule__ValidatorRules__ValidatorRulesAssignment_0");
					put(grammarAccess.getValidatorRulesAccess().getValidatorRulesAssignment_1_1(), "rule__ValidatorRules__ValidatorRulesAssignment_1_1");
					put(grammarAccess.getValidatorFeatureAccess().getNameAssignment_1(), "rule__ValidatorFeature__NameAssignment_1");
					put(grammarAccess.getValidatorFeatureAccess().getValidatorRulesAssignment_3(), "rule__ValidatorFeature__ValidatorRulesAssignment_3");
					put(grammarAccess.getValidatorModuleAccess().getValidatorFeaturesAssignment_2(), "rule__ValidatorModule__ValidatorFeaturesAssignment_2");
					put(grammarAccess.getValidatorModuleAccess().getValidatorFeaturesAssignment_3(), "rule__ValidatorModule__ValidatorFeaturesAssignment_3");
					put(grammarAccess.getScreenModelParameterAccess().getModelFeatureNameAssignment_0(), "rule__ScreenModelParameter__ModelFeatureNameAssignment_0");
					put(grammarAccess.getScreenModelParameterAccess().getModelFeatureValueAssignment_2(), "rule__ScreenModelParameter__ModelFeatureValueAssignment_2");
					put(grammarAccess.getScreenModelParametersAccess().getParametersAssignment_0(), "rule__ScreenModelParameters__ParametersAssignment_0");
					put(grammarAccess.getScreenModelParametersAccess().getParametersAssignment_1_1(), "rule__ScreenModelParameters__ParametersAssignment_1_1");
					put(grammarAccess.getNavigateToActionAccess().getScreenElementIdAssignment_1(), "rule__NavigateToAction__ScreenElementIdAssignment_1");
					put(grammarAccess.getNavigateToActionAccess().getModelFeaturesAssignment_2_1(), "rule__NavigateToAction__ModelFeaturesAssignment_2_1");
					put(grammarAccess.getExecuteActionAccess().getUiActionNameAssignment_1(), "rule__ExecuteAction__UiActionNameAssignment_1");
					put(grammarAccess.getSetRestCallReceiverURLParameterAccess().getParameterTypeAssignment_2(), "rule__SetRestCallReceiverURLParameter__ParameterTypeAssignment_2");
					put(grammarAccess.getSetRestCallReceiverReturnTypeParameterAccess().getParameterTypeAssignment_2(), "rule__SetRestCallReceiverReturnTypeParameter__ParameterTypeAssignment_2");
					put(grammarAccess.getSetRestCallReceiverIDParameterAccess().getParameterTypeAssignment_2(), "rule__SetRestCallReceiverIDParameter__ParameterTypeAssignment_2");
					put(grammarAccess.getSetRestCallReceiverParametersAccess().getParametersAssignment_0(), "rule__SetRestCallReceiverParameters__ParametersAssignment_0");
					put(grammarAccess.getSetRestCallReceiverParametersAccess().getParametersAssignment_1_1(), "rule__SetRestCallReceiverParameters__ParametersAssignment_1_1");
					put(grammarAccess.getSetRestCallReceiverAccess().getParametersAssignment_2(), "rule__SetRestCallReceiver__ParametersAssignment_2");
					put(grammarAccess.getSetUIElementReceiverAccess().getWidgetNameAssignment_0(), "rule__SetUIElementReceiver__WidgetNameAssignment_0");
					put(grammarAccess.getSetUIElementReceiverAccess().getUiKeyAssignment_2(), "rule__SetUIElementReceiver__UiKeyAssignment_2");
					put(grammarAccess.getSetActionAccess().getModelFeatureNameAssignment_1(), "rule__SetAction__ModelFeatureNameAssignment_1");
					put(grammarAccess.getSetActionAccess().getSetActionReceiverAssignment_3(), "rule__SetAction__SetActionReceiverAssignment_3");
					put(grammarAccess.getInterfaceMethodCallParameterAccess().getParameterNameAssignment_0(), "rule__InterfaceMethodCallParameter__ParameterNameAssignment_0");
					put(grammarAccess.getInterfaceMethodCallParameterAccess().getParameterTypeAssignment_2(), "rule__InterfaceMethodCallParameter__ParameterTypeAssignment_2");
					put(grammarAccess.getInterfaceMethodCallParametersAccess().getParametersAssignment_0(), "rule__InterfaceMethodCallParameters__ParametersAssignment_0");
					put(grammarAccess.getInterfaceMethodCallParametersAccess().getParametersAssignment_1_1(), "rule__InterfaceMethodCallParameters__ParametersAssignment_1_1");
					put(grammarAccess.getInterfaceMethodCallAccess().getInterfaceInstanceNameAssignment_0(), "rule__InterfaceMethodCall__InterfaceInstanceNameAssignment_0");
					put(grammarAccess.getInterfaceMethodCallAccess().getMethodNameAssignment_2(), "rule__InterfaceMethodCall__MethodNameAssignment_2");
					put(grammarAccess.getInterfaceMethodCallAccess().getParametersAssignment_4(), "rule__InterfaceMethodCall__ParametersAssignment_4");
					put(grammarAccess.getUIActionModuleAccess().getNameAssignment_1(), "rule__UIActionModule__NameAssignment_1");
					put(grammarAccess.getUIActionModuleAccess().getUiActionFeaturesAssignment_3(), "rule__UIActionModule__UiActionFeaturesAssignment_3");
					put(grammarAccess.getUIActionModuleAccess().getUiActionFeaturesAssignment_4(), "rule__UIActionModule__UiActionFeaturesAssignment_4");
					put(grammarAccess.getControllerModuleAccess().getElementsAssignment_2(), "rule__ControllerModule__ElementsAssignment_2");
					put(grammarAccess.getControllerModuleAccess().getElementsAssignment_3(), "rule__ControllerModule__ElementsAssignment_3");
					put(grammarAccess.getScreenFeatureAccess().getNameAssignment_1(), "rule__ScreenFeature__NameAssignment_1");
					put(grammarAccess.getScreenFeatureAccess().getScreenModulesAssignment_3(), "rule__ScreenFeature__ScreenModulesAssignment_3");
					put(grammarAccess.getScreenFeatureAccess().getScreenModulesAssignment_4(), "rule__ScreenFeature__ScreenModulesAssignment_4");
					put(grammarAccess.getMainFeatureOptionAccess().getNameAssignment_2(), "rule__MainFeatureOption__NameAssignment_2");
					put(grammarAccess.getMainFeatureAccess().getFeaturesAssignment_2(), "rule__MainFeature__FeaturesAssignment_2");
					put(grammarAccess.getMainFeatureAccess().getFeaturesAssignment_3_1(), "rule__MainFeature__FeaturesAssignment_3_1");
					put(grammarAccess.getUIModuleAccess().getUiFeaturesAssignment_2(), "rule__UIModule__UiFeaturesAssignment_2");
					put(grammarAccess.getUIModuleAccess().getUiFeaturesAssignment_3(), "rule__UIModule__UiFeaturesAssignment_3");
					put(grammarAccess.getBusinessFeatureAccess().getNameAssignment_1(), "rule__BusinessFeature__NameAssignment_1");
					put(grammarAccess.getBusinessFeatureAccess().getTypeAssignment_3(), "rule__BusinessFeature__TypeAssignment_3");
					put(grammarAccess.getBusinessFeatureAccess().getConnectPoint1Assignment_4_1(), "rule__BusinessFeature__ConnectPoint1Assignment_4_1");
					put(grammarAccess.getBusinessFeatureAccess().getConnectPoint2Assignment_4_3(), "rule__BusinessFeature__ConnectPoint2Assignment_4_3");
					put(grammarAccess.getBusinessFeatureAccess().getConnectEndAssignment_4_5(), "rule__BusinessFeature__ConnectEndAssignment_4_5");
					put(grammarAccess.getBusinessFeaturesAccess().getFeaturesAssignment_0(), "rule__BusinessFeatures__FeaturesAssignment_0");
					put(grammarAccess.getBusinessFeaturesAccess().getFeaturesAssignment_1(), "rule__BusinessFeatures__FeaturesAssignment_1");
					put(grammarAccess.getSystemDefinitionAccess().getNameAssignment_1(), "rule__SystemDefinition__NameAssignment_1");
					put(grammarAccess.getSystemDefinitionAccess().getModulesAssignment_3(), "rule__SystemDefinition__ModulesAssignment_3");
					put(grammarAccess.getSystemDefinitionAccess().getModulesAssignment_4(), "rule__SystemDefinition__ModulesAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.example.domainmodel.ui.contentassist.antlr.internal.InternalDomainmodelParser typedParser = (org.example.domainmodel.ui.contentassist.antlr.internal.InternalDomainmodelParser) parser;
			typedParser.entryRuleDomainmodel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DomainmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DomainmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
