/*
 * generated by Xtext
 */
package org.example.domainmodel.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

@SuppressWarnings("all")
public class DomainmodelSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DomainmodelGrammarAccess grammarAccess;
	protected AbstractElementAlias match_DataType_ConfigKeyword_4_q;
	protected AbstractElementAlias match_DataType_PersistableKeyword_6_q;
	protected AbstractElementAlias match_Feature_RefKeyword_0_q;
	protected AbstractElementAlias match_InterfaceOperationUsageRule_ProvidesKeyword_0_0_or_RequiresKeyword_0_1;
	protected AbstractElementAlias match_InterfaceOperation_LeftSquareBracketRightSquareBracketKeyword_5_q;
	protected AbstractElementAlias match_MainFeatureOption_AppNameKeyword_0_0_or_AppVersionKeyword_0_1_or_DevicesKeyword_0_3_or_EntryScreenKeyword_0_2_or_StyleKeyword_0_4;
	protected AbstractElementAlias match_ModelFeature___LeftSquareBracketRightSquareBracketKeyword_3_0_OrderedKeyword_3_1_q__q;
	protected AbstractElementAlias match_SetRestCallReceiverIDParameter_IdKeyword_0_0_or_UpdateKeyword_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DomainmodelGrammarAccess) access;
		match_DataType_ConfigKeyword_4_q = new TokenAlias(false, true, grammarAccess.getDataTypeAccess().getConfigKeyword_4());
		match_DataType_PersistableKeyword_6_q = new TokenAlias(false, true, grammarAccess.getDataTypeAccess().getPersistableKeyword_6());
		match_Feature_RefKeyword_0_q = new TokenAlias(false, true, grammarAccess.getFeatureAccess().getRefKeyword_0());
		match_InterfaceOperationUsageRule_ProvidesKeyword_0_0_or_RequiresKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getInterfaceOperationUsageRuleAccess().getProvidesKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getInterfaceOperationUsageRuleAccess().getRequiresKeyword_0_1()));
		match_InterfaceOperation_LeftSquareBracketRightSquareBracketKeyword_5_q = new TokenAlias(false, true, grammarAccess.getInterfaceOperationAccess().getLeftSquareBracketRightSquareBracketKeyword_5());
		match_MainFeatureOption_AppNameKeyword_0_0_or_AppVersionKeyword_0_1_or_DevicesKeyword_0_3_or_EntryScreenKeyword_0_2_or_StyleKeyword_0_4 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getMainFeatureOptionAccess().getAppNameKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getMainFeatureOptionAccess().getAppVersionKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getMainFeatureOptionAccess().getDevicesKeyword_0_3()), new TokenAlias(false, false, grammarAccess.getMainFeatureOptionAccess().getEntryScreenKeyword_0_2()), new TokenAlias(false, false, grammarAccess.getMainFeatureOptionAccess().getStyleKeyword_0_4()));
		match_ModelFeature___LeftSquareBracketRightSquareBracketKeyword_3_0_OrderedKeyword_3_1_q__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getModelFeatureAccess().getLeftSquareBracketRightSquareBracketKeyword_3_0()), new TokenAlias(false, true, grammarAccess.getModelFeatureAccess().getOrderedKeyword_3_1()));
		match_SetRestCallReceiverIDParameter_IdKeyword_0_0_or_UpdateKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getSetRestCallReceiverIDParameterAccess().getIdKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getSetRestCallReceiverIDParameterAccess().getUpdateKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_DataType_ConfigKeyword_4_q.equals(syntax))
				emit_DataType_ConfigKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_DataType_PersistableKeyword_6_q.equals(syntax))
				emit_DataType_PersistableKeyword_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Feature_RefKeyword_0_q.equals(syntax))
				emit_Feature_RefKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_InterfaceOperationUsageRule_ProvidesKeyword_0_0_or_RequiresKeyword_0_1.equals(syntax))
				emit_InterfaceOperationUsageRule_ProvidesKeyword_0_0_or_RequiresKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_InterfaceOperation_LeftSquareBracketRightSquareBracketKeyword_5_q.equals(syntax))
				emit_InterfaceOperation_LeftSquareBracketRightSquareBracketKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_MainFeatureOption_AppNameKeyword_0_0_or_AppVersionKeyword_0_1_or_DevicesKeyword_0_3_or_EntryScreenKeyword_0_2_or_StyleKeyword_0_4.equals(syntax))
				emit_MainFeatureOption_AppNameKeyword_0_0_or_AppVersionKeyword_0_1_or_DevicesKeyword_0_3_or_EntryScreenKeyword_0_2_or_StyleKeyword_0_4(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ModelFeature___LeftSquareBracketRightSquareBracketKeyword_3_0_OrderedKeyword_3_1_q__q.equals(syntax))
				emit_ModelFeature___LeftSquareBracketRightSquareBracketKeyword_3_0_OrderedKeyword_3_1_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_SetRestCallReceiverIDParameter_IdKeyword_0_0_or_UpdateKeyword_0_1.equals(syntax))
				emit_SetRestCallReceiverIDParameter_IdKeyword_0_0_or_UpdateKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'config'?
	 *
	 * This ambiguous syntax occurs at:
	 *     mappedType=QualifiedName (ambiguity) 'init' initValue=STRING
	 *     mappedType=QualifiedName (ambiguity) 'persistable'? (rule end)
	 */
	protected void emit_DataType_ConfigKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'persistable'?
	 *
	 * This ambiguous syntax occurs at:
	 *     initValue=STRING (ambiguity) (rule end)
	 *     mappedType=QualifiedName 'config'? (ambiguity) (rule end)
	 */
	protected void emit_DataType_PersistableKeyword_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'ref'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_Feature_RefKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'provides' | 'requires'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_InterfaceOperationUsageRule_ProvidesKeyword_0_0_or_RequiresKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '[]'?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[Type|QualifiedName] (ambiguity) (rule end)
	 */
	protected void emit_InterfaceOperation_LeftSquareBracketRightSquareBracketKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'appName' | 'appVersion' | 'entryScreen' | 'devices' | 'style'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ':' name=STRING
	 */
	protected void emit_MainFeatureOption_AppNameKeyword_0_0_or_AppVersionKeyword_0_1_or_DevicesKeyword_0_3_or_EntryScreenKeyword_0_2_or_StyleKeyword_0_4(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('[]' 'ordered'?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[Type|QualifiedName] (ambiguity) (rule end)
	 */
	protected void emit_ModelFeature___LeftSquareBracketRightSquareBracketKeyword_3_0_OrderedKeyword_3_1_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'id' | 'update'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ':' parameterType=ID
	 */
	protected void emit_SetRestCallReceiverIDParameter_IdKeyword_0_0_or_UpdateKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
