/**
 * generated by Xtext
 */
package com.nagarro.validation;

import com.nagarro.validation.AbstractAppBuilderDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AppBuilderDSLValidator extends AbstractAppBuilderDSLValidator {
}
