/*
 * generated by Xtext
 */
package com.nagarro;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AppBuilderDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.nagarro.ui.internal.AppBuilderDSLActivator.getInstance().getInjector("com.nagarro.AppBuilderDSL");
	}
	
}
