/*
 * generated by Xtext
 */
package org.example.domainmodel.ui.contentassist

import org.example.domainmodel.ui.contentassist.AbstractDomainmodelProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DomainmodelProposalProvider extends AbstractDomainmodelProposalProvider {
}
