/*
 * generated by Xtext
 */
package com.nagarro.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.nagarro.ui.internal.AppBuilderDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AppBuilderDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AppBuilderDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AppBuilderDSLActivator.getInstance().getInjector(AppBuilderDSLActivator.COM_NAGARRO_APPBUILDERDSL);
	}
	
}
