/*
 * generated by Xtext
 */
package com.nagarro.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AppBuilderDSLUiModule extends com.nagarro.ui.AbstractAppBuilderDSLUiModule {
	public AppBuilderDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
