/*
 * generated by Xtext
 */
package com.nagarro.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.nagarro.services.AppBuilderDSLGrammarAccess;

public class AppBuilderDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private AppBuilderDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.nagarro.ui.contentassist.antlr.internal.InternalAppBuilderDSLParser createParser() {
		com.nagarro.ui.contentassist.antlr.internal.InternalAppBuilderDSLParser result = new com.nagarro.ui.contentassist.antlr.internal.InternalAppBuilderDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
					put(grammarAccess.getScreenAccess().getAlternatives(), "rule__Screen__Alternatives");
					put(grammarAccess.getDataBindingAccess().getAlternatives(), "rule__DataBinding__Alternatives");
					put(grammarAccess.getConditionExpressionAccess().getAlternatives(), "rule__ConditionExpression__Alternatives");
					put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
					put(grammarAccess.getSetInstructionAssignmentAccess().getAlternatives(), "rule__SetInstructionAssignment__Alternatives");
					put(grammarAccess.getLayoutAccess().getAlternatives_0(), "rule__Layout__Alternatives_0");
					put(grammarAccess.getControlAccess().getAlternatives(), "rule__Control__Alternatives");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getExpressionTermAccess().getAlternatives(), "rule__ExpressionTerm__Alternatives");
					put(grammarAccess.getASEPARATORAccess().getAlternatives(), "rule__ASEPARATOR__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getDeviceAccess().getAlternatives(), "rule__Device__Alternatives");
					put(grammarAccess.getNamespaceDeclationAccess().getGroup(), "rule__NamespaceDeclation__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getBusinessAccess().getGroup(), "rule__Business__Group__0");
					put(grammarAccess.getInstanceServiceAccess().getGroup(), "rule__InstanceService__Group__0");
					put(grammarAccess.getUiAccess().getGroup(), "rule__Ui__Group__0");
					put(grammarAccess.getMainAccess().getGroup(), "rule__Main__Group__0");
					put(grammarAccess.getMainAccess().getGroup_3_0(), "rule__Main__Group_3_0__0");
					put(grammarAccess.getMainAccess().getGroup_3_1(), "rule__Main__Group_3_1__0");
					put(grammarAccess.getMainAccess().getGroup_3_2(), "rule__Main__Group_3_2__0");
					put(grammarAccess.getMainAccess().getGroup_3_2_3(), "rule__Main__Group_3_2_3__0");
					put(grammarAccess.getMainAccess().getGroup_3_2_3_1(), "rule__Main__Group_3_2_3_1__0");
					put(grammarAccess.getMainAccess().getGroup_3_3(), "rule__Main__Group_3_3__0");
					put(grammarAccess.getMainAccess().getGroup_3_4(), "rule__Main__Group_3_4__0");
					put(grammarAccess.getSimpleScreenAccess().getGroup(), "rule__SimpleScreen__Group__0");
					put(grammarAccess.getEntryParametersAccess().getGroup(), "rule__EntryParameters__Group__0");
					put(grammarAccess.getControllerAccess().getGroup(), "rule__Controller__Group__0");
					put(grammarAccess.getInitActionAccess().getGroup(), "rule__InitAction__Group__0");
					put(grammarAccess.getValidationBindingAccess().getGroup(), "rule__ValidationBinding__Group__0");
					put(grammarAccess.getValidationBindingAccess().getGroup_4(), "rule__ValidationBinding__Group_4__0");
					put(grammarAccess.getUiListenerBindingAccess().getGroup(), "rule__UiListenerBinding__Group__0");
					put(grammarAccess.getUiListenerBindingAccess().getGroup_4(), "rule__UiListenerBinding__Group_4__0");
					put(grammarAccess.getSimpleDataBindingAccess().getGroup(), "rule__SimpleDataBinding__Group__0");
					put(grammarAccess.getSimpleDataBindingAccess().getGroup_2(), "rule__SimpleDataBinding__Group_2__0");
					put(grammarAccess.getSimpleDataBindingAccess().getGroup_5(), "rule__SimpleDataBinding__Group_5__0");
					put(grammarAccess.getEnumDataBindingAccess().getGroup(), "rule__EnumDataBinding__Group__0");
					put(grammarAccess.getEnumDataBindingAccess().getGroup_9(), "rule__EnumDataBinding__Group_9__0");
					put(grammarAccess.getValidatorAccess().getGroup(), "rule__Validator__Group__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getSimpleConditionExpressionAccess().getGroup(), "rule__SimpleConditionExpression__Group__0");
					put(grammarAccess.getCompositeConditionExpressionAccess().getGroup(), "rule__CompositeConditionExpression__Group__0");
					put(grammarAccess.getCompositeConditionExpressionAccess().getGroup_1(), "rule__CompositeConditionExpression__Group_1__0");
					put(grammarAccess.getUiActionAccess().getGroup(), "rule__UiAction__Group__0");
					put(grammarAccess.getSetInstructionAccess().getGroup(), "rule__SetInstruction__Group__0");
					put(grammarAccess.getSetInstructionAccess().getGroup_2(), "rule__SetInstruction__Group_2__0");
					put(grammarAccess.getNavigateAccess().getGroup(), "rule__Navigate__Group__0");
					put(grammarAccess.getNavigateAccess().getGroup_2(), "rule__Navigate__Group_2__0");
					put(grammarAccess.getNavigateAccess().getGroup_2_1(), "rule__Navigate__Group_2_1__0");
					put(grammarAccess.getExecuteActionAccess().getGroup(), "rule__ExecuteAction__Group__0");
					put(grammarAccess.getSetInstructionAssignmentAccess().getGroup_1(), "rule__SetInstructionAssignment__Group_1__0");
					put(grammarAccess.getSetInstructionAssignmentAccess().getGroup_2(), "rule__SetInstructionAssignment__Group_2__0");
					put(grammarAccess.getRestCallAccess().getGroup(), "rule__RestCall__Group__0");
					put(grammarAccess.getRestCallAccess().getGroup_2(), "rule__RestCall__Group_2__0");
					put(grammarAccess.getRestCallAccess().getGroup_4(), "rule__RestCall__Group_4__0");
					put(grammarAccess.getControlValueAccess().getGroup(), "rule__ControlValue__Group__0");
					put(grammarAccess.getControlValueAccess().getGroup_1(), "rule__ControlValue__Group_1__0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getViewAccess().getGroup(), "rule__View__Group__0");
					put(grammarAccess.getLayoutAccess().getGroup(), "rule__Layout__Group__0");
					put(grammarAccess.getGridLayoutAccess().getGroup(), "rule__GridLayout__Group__0");
					put(grammarAccess.getGridLayoutAccess().getGroup_6(), "rule__GridLayout__Group_6__0");
					put(grammarAccess.getRowLayoutAccess().getGroup(), "rule__RowLayout__Group__0");
					put(grammarAccess.getScreenLayoutAccess().getGroup(), "rule__ScreenLayout__Group__0");
					put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
					put(grammarAccess.getListAccess().getGroup_3_0(), "rule__List__Group_3_0__0");
					put(grammarAccess.getListAccess().getGroup_3_1(), "rule__List__Group_3_1__0");
					put(grammarAccess.getListAccess().getGroup_3_2(), "rule__List__Group_3_2__0");
					put(grammarAccess.getValueAccess().getGroup_0(), "rule__Value__Group_0__0");
					put(grammarAccess.getDynamicValueAccess().getGroup(), "rule__DynamicValue__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getTextAccess().getGroup_3_0(), "rule__Text__Group_3_0__0");
					put(grammarAccess.getTextAccess().getGroup_3_1(), "rule__Text__Group_3_1__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getButtonAccess().getGroup_3_0(), "rule__Button__Group_3_0__0");
					put(grammarAccess.getButtonAccess().getGroup_3_1(), "rule__Button__Group_3_1__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getLabelAccess().getGroup_3(), "rule__Label__Group_3__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getCompositeScreenAccess().getGroup(), "rule__CompositeScreen__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getEntityAccess().getGroup_2(), "rule__Entity__Group_2__0");
					put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
					put(grammarAccess.getAppBuilderAccess().getElementsAssignment(), "rule__AppBuilder__ElementsAssignment");
					put(grammarAccess.getNamespaceDeclationAccess().getNameAssignment_1(), "rule__NamespaceDeclation__NameAssignment_1");
					put(grammarAccess.getSystemAccess().getNameAssignment_1(), "rule__System__NameAssignment_1");
					put(grammarAccess.getSystemAccess().getBusinessAssignment_3(), "rule__System__BusinessAssignment_3");
					put(grammarAccess.getSystemAccess().getUiAssignment_4(), "rule__System__UiAssignment_4");
					put(grammarAccess.getBusinessAccess().getElementsAssignment_3(), "rule__Business__ElementsAssignment_3");
					put(grammarAccess.getInstanceServiceAccess().getInstanceNameAssignment_1(), "rule__InstanceService__InstanceNameAssignment_1");
					put(grammarAccess.getUiAccess().getMainAssignment_2(), "rule__Ui__MainAssignment_2");
					put(grammarAccess.getUiAccess().getServicesAssignment_3(), "rule__Ui__ServicesAssignment_3");
					put(grammarAccess.getUiAccess().getScreensAssignment_4(), "rule__Ui__ScreensAssignment_4");
					put(grammarAccess.getMainAccess().getAppNameAssignment_3_0_2(), "rule__Main__AppNameAssignment_3_0_2");
					put(grammarAccess.getMainAccess().getAppVersionAssignment_3_1_2(), "rule__Main__AppVersionAssignment_3_1_2");
					put(grammarAccess.getMainAccess().getDevicesAssignment_3_2_3_0(), "rule__Main__DevicesAssignment_3_2_3_0");
					put(grammarAccess.getMainAccess().getDevicesAssignment_3_2_3_1_1(), "rule__Main__DevicesAssignment_3_2_3_1_1");
					put(grammarAccess.getMainAccess().getScreenAssignment_3_3_2(), "rule__Main__ScreenAssignment_3_3_2");
					put(grammarAccess.getMainAccess().getGeneralStyleAssignment_3_4_2(), "rule__Main__GeneralStyleAssignment_3_4_2");
					put(grammarAccess.getSimpleScreenAccess().getNameAssignment_1(), "rule__SimpleScreen__NameAssignment_1");
					put(grammarAccess.getSimpleScreenAccess().getEntryParametersAssignment_3(), "rule__SimpleScreen__EntryParametersAssignment_3");
					put(grammarAccess.getSimpleScreenAccess().getModelAssignment_4(), "rule__SimpleScreen__ModelAssignment_4");
					put(grammarAccess.getSimpleScreenAccess().getViewAssignment_5(), "rule__SimpleScreen__ViewAssignment_5");
					put(grammarAccess.getSimpleScreenAccess().getControllerAssignment_6(), "rule__SimpleScreen__ControllerAssignment_6");
					put(grammarAccess.getEntryParametersAccess().getAttributesAssignment_2(), "rule__EntryParameters__AttributesAssignment_2");
					put(grammarAccess.getControllerAccess().getInitActionAssignment_2(), "rule__Controller__InitActionAssignment_2");
					put(grammarAccess.getControllerAccess().getValidatorAssignment_3(), "rule__Controller__ValidatorAssignment_3");
					put(grammarAccess.getControllerAccess().getActionsAssignment_4(), "rule__Controller__ActionsAssignment_4");
					put(grammarAccess.getInitActionAccess().getDatabindingsAssignment_3(), "rule__InitAction__DatabindingsAssignment_3");
					put(grammarAccess.getInitActionAccess().getUiListenerBindingssAssignment_4(), "rule__InitAction__UiListenerBindingssAssignment_4");
					put(grammarAccess.getInitActionAccess().getValidationBindingsAssignment_5(), "rule__InitAction__ValidationBindingsAssignment_5");
					put(grammarAccess.getInitActionAccess().getInstructionsAssignment_6(), "rule__InitAction__InstructionsAssignment_6");
					put(grammarAccess.getValidationBindingAccess().getConditionAssignment_1(), "rule__ValidationBinding__ConditionAssignment_1");
					put(grammarAccess.getValidationBindingAccess().getControlAssignment_3(), "rule__ValidationBinding__ControlAssignment_3");
					put(grammarAccess.getValidationBindingAccess().getControlAccessAssignment_4_1(), "rule__ValidationBinding__ControlAccessAssignment_4_1");
					put(grammarAccess.getUiListenerBindingAccess().getActionAssignment_1(), "rule__UiListenerBinding__ActionAssignment_1");
					put(grammarAccess.getUiListenerBindingAccess().getControlAssignment_3(), "rule__UiListenerBinding__ControlAssignment_3");
					put(grammarAccess.getUiListenerBindingAccess().getControlAccessAssignment_4_1(), "rule__UiListenerBinding__ControlAccessAssignment_4_1");
					put(grammarAccess.getSimpleDataBindingAccess().getModelAssignment_1(), "rule__SimpleDataBinding__ModelAssignment_1");
					put(grammarAccess.getSimpleDataBindingAccess().getModelAccessAssignment_2_1(), "rule__SimpleDataBinding__ModelAccessAssignment_2_1");
					put(grammarAccess.getSimpleDataBindingAccess().getControlAssignment_4(), "rule__SimpleDataBinding__ControlAssignment_4");
					put(grammarAccess.getSimpleDataBindingAccess().getControlAccessAssignment_5_1(), "rule__SimpleDataBinding__ControlAccessAssignment_5_1");
					put(grammarAccess.getEnumDataBindingAccess().getEnumClassNameAssignment_5(), "rule__EnumDataBinding__EnumClassNameAssignment_5");
					put(grammarAccess.getEnumDataBindingAccess().getControlAssignment_8(), "rule__EnumDataBinding__ControlAssignment_8");
					put(grammarAccess.getEnumDataBindingAccess().getControlAccessAssignment_9_1(), "rule__EnumDataBinding__ControlAccessAssignment_9_1");
					put(grammarAccess.getValidatorAccess().getConditionsAssignment_3(), "rule__Validator__ConditionsAssignment_3");
					put(grammarAccess.getConditionAccess().getNameAssignment_1(), "rule__Condition__NameAssignment_1");
					put(grammarAccess.getConditionAccess().getConditionExpressionAssignment_3(), "rule__Condition__ConditionExpressionAssignment_3");
					put(grammarAccess.getSimpleConditionExpressionAccess().getVariableNameAssignment_0(), "rule__SimpleConditionExpression__VariableNameAssignment_0");
					put(grammarAccess.getCompositeConditionExpressionAccess().getConditionsAssignment_0(), "rule__CompositeConditionExpression__ConditionsAssignment_0");
					put(grammarAccess.getCompositeConditionExpressionAccess().getConditionsAssignment_1_1(), "rule__CompositeConditionExpression__ConditionsAssignment_1_1");
					put(grammarAccess.getUiActionAccess().getNameAssignment_1(), "rule__UiAction__NameAssignment_1");
					put(grammarAccess.getUiActionAccess().getInstructionsAssignment_3(), "rule__UiAction__InstructionsAssignment_3");
					put(grammarAccess.getSetInstructionAccess().getModelAssignment_1(), "rule__SetInstruction__ModelAssignment_1");
					put(grammarAccess.getSetInstructionAccess().getModelAccessAssignment_2_1(), "rule__SetInstruction__ModelAccessAssignment_2_1");
					put(grammarAccess.getSetInstructionAccess().getAssignmentAssignment_4(), "rule__SetInstruction__AssignmentAssignment_4");
					put(grammarAccess.getNavigateAccess().getScreenAssignment_1(), "rule__Navigate__ScreenAssignment_1");
					put(grammarAccess.getNavigateAccess().getParamsAssignment_2_1_0(), "rule__Navigate__ParamsAssignment_2_1_0");
					put(grammarAccess.getExecuteActionAccess().getActionAssignment_1(), "rule__ExecuteAction__ActionAssignment_1");
					put(grammarAccess.getRestCallAccess().getUrlAssignment_2_2(), "rule__RestCall__UrlAssignment_2_2");
					put(grammarAccess.getControlValueAccess().getControlAssignment_0(), "rule__ControlValue__ControlAssignment_0");
					put(grammarAccess.getControlValueAccess().getControlAccessAssignment_1_1(), "rule__ControlValue__ControlAccessAssignment_1_1");
					put(grammarAccess.getModelAccess().getAttributesAssignment_3(), "rule__Model__AttributesAssignment_3");
					put(grammarAccess.getViewAccess().getLayoutsAssignment_2(), "rule__View__LayoutsAssignment_2");
					put(grammarAccess.getLayoutAccess().getControlsAssignment_2(), "rule__Layout__ControlsAssignment_2");
					put(grammarAccess.getGridLayoutAccess().getTypeAssignment_4(), "rule__GridLayout__TypeAssignment_4");
					put(grammarAccess.getGridLayoutAccess().getColumnsAssignment_6_2(), "rule__GridLayout__ColumnsAssignment_6_2");
					put(grammarAccess.getRowLayoutAccess().getTypeAssignment_4(), "rule__RowLayout__TypeAssignment_4");
					put(grammarAccess.getScreenLayoutAccess().getScreenAssignment_1(), "rule__ScreenLayout__ScreenAssignment_1");
					put(grammarAccess.getListAccess().getNameAssignment_1(), "rule__List__NameAssignment_1");
					put(grammarAccess.getListAccess().getLabelproviderAssignment_3_0_2(), "rule__List__LabelproviderAssignment_3_0_2");
					put(grammarAccess.getListAccess().getCssStyleAssignment_3_1_2(), "rule__List__CssStyleAssignment_3_1_2");
					put(grammarAccess.getListAccess().getTooltipAssignment_3_2_2(), "rule__List__TooltipAssignment_3_2_2");
					put(grammarAccess.getDynamicValueAccess().getVariableNameAssignment_1(), "rule__DynamicValue__VariableNameAssignment_1");
					put(grammarAccess.getDynamicValueAccess().getTypeAssignment_3(), "rule__DynamicValue__TypeAssignment_3");
					put(grammarAccess.getDynamicValueAccess().getExpressionAssignment_5(), "rule__DynamicValue__ExpressionAssignment_5");
					put(grammarAccess.getExpressionAccess().getTermsAssignment_0(), "rule__Expression__TermsAssignment_0");
					put(grammarAccess.getExpressionAccess().getTermsAssignment_1_1(), "rule__Expression__TermsAssignment_1_1");
					put(grammarAccess.getTextAccess().getNameAssignment_1(), "rule__Text__NameAssignment_1");
					put(grammarAccess.getTextAccess().getCssStyleAssignment_3_0_2(), "rule__Text__CssStyleAssignment_3_0_2");
					put(grammarAccess.getTextAccess().getResourceKeyAssignment_3_1_2(), "rule__Text__ResourceKeyAssignment_3_1_2");
					put(grammarAccess.getButtonAccess().getNameAssignment_1(), "rule__Button__NameAssignment_1");
					put(grammarAccess.getButtonAccess().getCssStyleAssignment_3_0_2(), "rule__Button__CssStyleAssignment_3_0_2");
					put(grammarAccess.getButtonAccess().getResourceKeyAssignment_3_1_2(), "rule__Button__ResourceKeyAssignment_3_1_2");
					put(grammarAccess.getLabelAccess().getNameAssignment_1(), "rule__Label__NameAssignment_1");
					put(grammarAccess.getLabelAccess().getResourceKeyAssignment_3_2(), "rule__Label__ResourceKeyAssignment_3_2");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
					put(grammarAccess.getCompositeScreenAccess().getNameAssignment_1(), "rule__CompositeScreen__NameAssignment_1");
					put(grammarAccess.getCompositeScreenAccess().getLayoutsAssignment_5(), "rule__CompositeScreen__LayoutsAssignment_5");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getDataTypeAccess().getNameAssignment_1(), "rule__DataType__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getSuperTypeAssignment_2_1(), "rule__Entity__SuperTypeAssignment_2_1");
					put(grammarAccess.getEntityAccess().getFeaturesAssignment_4(), "rule__Entity__FeaturesAssignment_4");
					put(grammarAccess.getFeatureAccess().getManyAssignment_0(), "rule__Feature__ManyAssignment_0");
					put(grammarAccess.getFeatureAccess().getNameAssignment_1(), "rule__Feature__NameAssignment_1");
					put(grammarAccess.getFeatureAccess().getTypeAssignment_3(), "rule__Feature__TypeAssignment_3");
					put(grammarAccess.getMainAccess().getUnorderedGroup_3(), "rule__Main__UnorderedGroup_3");
					put(grammarAccess.getListAccess().getUnorderedGroup_3(), "rule__List__UnorderedGroup_3");
					put(grammarAccess.getTextAccess().getUnorderedGroup_3(), "rule__Text__UnorderedGroup_3");
					put(grammarAccess.getButtonAccess().getUnorderedGroup_3(), "rule__Button__UnorderedGroup_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.nagarro.ui.contentassist.antlr.internal.InternalAppBuilderDSLParser typedParser = (com.nagarro.ui.contentassist.antlr.internal.InternalAppBuilderDSLParser) parser;
			typedParser.entryRuleAppBuilder();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AppBuilderDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AppBuilderDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
