/*
 * generated by Xtext
 */
package com.nagarro.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.nagarro.services.AppBuilderDSLGrammarAccess;

public class AppBuilderDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AppBuilderDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.nagarro.parser.antlr.internal.InternalAppBuilderDSLParser createParser(XtextTokenStream stream) {
		return new com.nagarro.parser.antlr.internal.InternalAppBuilderDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AppBuilder";
	}
	
	public AppBuilderDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AppBuilderDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
