/*
 * generated by Xtext
 */
package com.nagarro;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AppBuilderDSLRuntimeModule extends com.nagarro.AbstractAppBuilderDSLRuntimeModule {

}
